name: Test Unit 

on:

  push:
    branches: ["feature/**", "fix/**", "chore/**", "*" ]
    
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 23 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "23"
          cache: maven

      - name: Run unit tests
        run: mvn -B -DskipTests=false test

      - name: Publicar reportes Surefire
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            **/target/surefire-reports/*.xml
            **/target/surefire-reports/*.txt
